// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq6hdGGKOWfLv_lZO3l4jG-GgVZ6RKgpQ',
    appId: '1:1013284984506:web:6c2db480a0ad372bd45483',
    messagingSenderId: '1013284984506',
    projectId: 'flutter-bbb5a',
    authDomain: 'flutter-bbb5a.firebaseapp.com',
    storageBucket: 'flutter-bbb5a.appspot.com',
    measurementId: 'G-5H62N3LR95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAH-3282H0JmCFMI4bb9f9_a_FwhOJ428',
    appId: '1:1013284984506:android:b6ab40baeadd5cc8d45483',
    messagingSenderId: '1013284984506',
    projectId: 'flutter-bbb5a',
    storageBucket: 'flutter-bbb5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJCC2ErBRqchzhcYw2RdHNr2qEk1xCWh8',
    appId: '1:1013284984506:ios:2e813422dfe84792d45483',
    messagingSenderId: '1013284984506',
    projectId: 'flutter-bbb5a',
    storageBucket: 'flutter-bbb5a.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJCC2ErBRqchzhcYw2RdHNr2qEk1xCWh8',
    appId: '1:1013284984506:ios:2e813422dfe84792d45483',
    messagingSenderId: '1013284984506',
    projectId: 'flutter-bbb5a',
    storageBucket: 'flutter-bbb5a.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq6hdGGKOWfLv_lZO3l4jG-GgVZ6RKgpQ',
    appId: '1:1013284984506:web:bf7edb9b5601e39dd45483',
    messagingSenderId: '1013284984506',
    projectId: 'flutter-bbb5a',
    authDomain: 'flutter-bbb5a.firebaseapp.com',
    storageBucket: 'flutter-bbb5a.appspot.com',
    measurementId: 'G-SLZ9C3JWWW',
  );
}
